apiVersion: workload.codeflare.dev/v1beta1
kind: AppWrapper
metadata:
  labels:
    orderedinstance: m5.xlarge_g4dn.xlarge
  name: interactivetest
  namespace: default
spec:
  priority: 9
  resources:
    GenericItems:
    - custompodresources:
      - limits:
          cpu: 2
          memory: 8G
          nvidia.com/gpu: 0
        replicas: 1
        requests:
          cpu: 2
          memory: 8G
          nvidia.com/gpu: 0
      - limits:
          cpu: 2
          memory: 8G
          nvidia.com/gpu: 1
        replicas: 2
        requests:
          cpu: 2
          memory: 8G
          nvidia.com/gpu: 1
      generictemplate:
        apiVersion: ray.io/v1
        kind: RayCluster
        metadata:
          labels:
            appwrapper.mcad.ibm.com: interactivetest
            controller-tools.k8s.io: '1.0'
          name: interactivetest
          namespace: default
        spec:
          autoscalerOptions:
            idleTimeoutSeconds: 60
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 500m
                memory: 512Mi
            upscalingMode: Default
          enableInTreeAutoscaling: false
          headGroupSpec:
            rayStartParams:
              block: 'true'
              dashboard-host: 0.0.0.0
              num-gpus: '0'
            serviceType: ClusterIP
            template:
              spec:
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: interactivetest
                          operator: In
                          values:
                          - interactivetest
                containers:
                - env:
                  - name: MY_POD_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                  - name: RAY_USE_TLS
                    value: '0'
                  - name: RAY_TLS_SERVER_CERT
                    value: /home/ray/workspace/tls/server.crt
                  - name: RAY_TLS_SERVER_KEY
                    value: /home/ray/workspace/tls/server.key
                  - name: RAY_TLS_CA_CERT
                    value: /home/ray/workspace/tls/ca.crt
                  image: quay.io/rhoai/ray:2.23.0-py39-cu121
                  imagePullPolicy: Always
                  lifecycle:
                    preStop:
                      exec:
                        command:
                        - /bin/sh
                        - -c
                        - ray stop
                  name: ray-head
                  ports:
                  - containerPort: 6379
                    name: gcs
                  - containerPort: 8265
                    name: dashboard
                  - containerPort: 10001
                    name: client
                  resources:
                    limits:
                      cpu: 2
                      memory: 8G
                      nvidia.com/gpu: 0
                    requests:
                      cpu: 2
                      memory: 8G
                      nvidia.com/gpu: 0
                imagePullSecrets: []
          rayVersion: 2.1.0
          workerGroupSpecs:
          - groupName: small-group-interactivetest
            maxReplicas: 2
            minReplicas: 2
            rayStartParams:
              block: 'true'
              num-gpus: '1'
            replicas: 2
            template:
              metadata:
                annotations:
                  key: value
                labels:
                  key: value
              spec:
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                      - matchExpressions:
                        - key: interactivetest
                          operator: In
                          values:
                          - interactivetest
                containers:
                - env:
                  - name: MY_POD_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                  - name: RAY_USE_TLS
                    value: '0'
                  - name: RAY_TLS_SERVER_CERT
                    value: /home/ray/workspace/tls/server.crt
                  - name: RAY_TLS_SERVER_KEY
                    value: /home/ray/workspace/tls/server.key
                  - name: RAY_TLS_CA_CERT
                    value: /home/ray/workspace/tls/ca.crt
                  image: quay.io/rhoai/ray:2.23.0-py39-cu121
                  lifecycle:
                    preStop:
                      exec:
                        command:
                        - /bin/sh
                        - -c
                        - ray stop
                  name: machine-learning
                  resources:
                    limits:
                      cpu: 2
                      memory: 8G
                      nvidia.com/gpu: 1
                    requests:
                      cpu: 2
                      memory: 8G
                      nvidia.com/gpu: 1
                imagePullSecrets: []
      replicas: 1
    - generictemplate:
        apiVersion: route.openshift.io/v1
        kind: Route
        metadata:
          labels:
            odh-ray-cluster-service: interactivetest-head-svc
          name: ray-dashboard-interactivetest
          namespace: default
        spec:
          port:
            targetPort: dashboard
          to:
            kind: Service
            name: interactivetest-head-svc
      replicas: 1
    Items: []
