#!/usr/bin/env python3
# Copyright 2024 IBM, Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
RayCluster Migration Tool for RHOAI 2.x to RHOAI 3.x

This script helps migrate RayClusters during RHOAI upgrades. It is designed
to be run in stages, allowing you to test the migration on a single cluster
before proceeding to an entire namespace or the whole Kubernetes cluster.

RECOMMENDED WORKFLOW:
    1. Run pre-upgrade to backup your RayCluster configurations
    2. Perform the RHOAI upgrade
    3. Run post-upgrade to migrate your RayClusters

REQUIREMENTS:
    - kubernetes>=28.1.0
    - PyYAML>=6.0

USAGE EXAMPLES:

    # Step 1: Backup - All clusters (you'll be prompted for backup directory)
    python ray_cluster_migration.py pre-upgrade

    # Step 1: Backup - With specific directory
    python ray_cluster_migration.py pre-upgrade ./my-backup-dir

    # Step 1: Backup - Specific namespace
    python ray_cluster_migration.py pre-upgrade --namespace my-ns

    # Step 1: Backup - Single cluster
    python ray_cluster_migration.py pre-upgrade --cluster my-cluster --namespace my-ns

    # ... Perform RHOAI upgrade ...

    # Step 2: Migrate - Start with the same single cluster
    python ray_cluster_migration.py post-upgrade --cluster my-cluster --namespace my-ns --dry-run
    python ray_cluster_migration.py post-upgrade --cluster my-cluster --namespace my-ns

    # Step 2: Migrate - Then proceed with entire namespace
    python ray_cluster_migration.py post-upgrade --namespace my-ns --dry-run
    python ray_cluster_migration.py post-upgrade --namespace my-ns

    # Step 2: Migrate - Finally, migrate all clusters (you'll be prompted to confirm)
    python ray_cluster_migration.py post-upgrade --dry-run
    python ray_cluster_migration.py post-upgrade

    # Discovery - List all RayClusters and their migration status
    python ray_cluster_migration.py list
    python ray_cluster_migration.py list --namespace my-ns

IDEMPOTENCY:
    All operations are idempotent and safe to run multiple times:
    - pre-upgrade: Overwrites backup files if they already exist
    - post-upgrade: Detects already-migrated clusters and skips them

AUTHENTICATION:
    The script uses standard Kubernetes authentication methods:
    1. KUBECONFIG environment variable
    2. ~/.kube/config file
    3. In-cluster config (when running in a pod)
"""

import os
import sys
import yaml
import copy
import argparse
from typing import List, Dict, Optional, Tuple
from kubernetes import client, config
from kubernetes.dynamic import DynamicClient
from kubernetes.client.rest import ApiException

# Field manager identifier for server-side apply
CF_SDK_FIELD_MANAGER = "codeflare-sdk"

# Annotation that marks a cluster as migrated
SECURE_NETWORK_ANNOTATION = "odh.ray.io/secure-trusted-network"

# Gateway API constants
GATEWAY_API_GROUP = "gateway.networking.k8s.io"
GATEWAY_API_VERSION = "v1"


def config_check():
    """
    Check and load the Kubernetes config from the default location.

    This function checks if a Kubernetes config file exists at the default path
    (~/.kube/config). If none is provided, it tries to load in-cluster config.

    Raises:
        RuntimeError: If no valid credentials or config file is found.
    """
    home_directory = os.path.expanduser("~")

    # Try to load kube config if not already loaded
    try:
        # First try to load from default location
        if os.path.isfile(f"{home_directory}/.kube/config"):
            config.load_kube_config()
        # Then try in-cluster config
        elif "KUBERNETES_PORT" in os.environ:
            config.load_incluster_config()
        else:
            raise RuntimeError(
                "No Kubernetes configuration found. Please ensure you have a valid "
                "~/.kube/config file or are running in a Kubernetes cluster."
            )
    except config.ConfigException as e:
        raise RuntimeError(f"Failed to load Kubernetes configuration: {e}")


def get_api_client() -> client.ApiClient:
    """
    Retrieve the Kubernetes API client with the default configuration.

    Returns:
        client.ApiClient: The Kubernetes API client object.
    """
    return client.ApiClient()


def remove_autogenerated_fields(resource):
    """
    Recursively remove autogenerated fields from a dictionary.

    This removes Kubernetes metadata fields that are auto-generated and should
    not be included when re-applying resources to a different cluster.

    Args:
        resource: Dictionary or list to process (modified in-place)
    """
    if isinstance(resource, dict):
        for key in list(resource.keys()):
            if key in [
                "creationTimestamp",
                "resourceVersion",
                "uid",
                "selfLink",
                "managedFields",
                "finalizers",
                "generation",
                "status",
                "suspend",
                "workload.codeflare.dev/user",  # AppWrapper field
                "workload.codeflare.dev/userid",  # AppWrapper field
                "podSetInfos",  # AppWrapper field
            ]:
                del resource[key]
            else:
                remove_autogenerated_fields(resource[key])

    elif isinstance(resource, list):
        for item in resource:
            remove_autogenerated_fields(item)


def _has_tls_oauth_components(ray_cluster_yaml: dict) -> Tuple[bool, List[str]]:
    """
    Check if a RayCluster has TLS/OAuth components that need migration.

    Returns:
        Tuple[bool, List[str]]: (has_components, list of component descriptions)
    """
    components_found = []

    # Environment variable names to check (TLS/OAuth related)
    tls_env_vars = {
        "RAY_USE_TLS",
        "RAY_TLS_SERVER_CERT",
        "RAY_TLS_SERVER_KEY",
        "RAY_TLS_CA_CERT",
    }

    # Volume names to check
    volumes_to_check = {"ca-vol", "proxy-tls-secret"}

    # Container names to check (sidecar containers)
    containers_to_check = {"oauth-proxy"}

    def check_pod_spec(pod_spec, group_name):
        """Check a pod spec for TLS/OAuth components."""
        # Check containers for oauth-proxy sidecar
        if "containers" in pod_spec:
            for container in pod_spec["containers"]:
                if container.get("name") in containers_to_check:
                    components_found.append(
                        f"{group_name}: oauth-proxy sidecar container"
                    )
                # Check for TLS env vars
                if "env" in container:
                    for env_var in container["env"]:
                        if env_var.get("name") in tls_env_vars:
                            components_found.append(
                                f"{group_name}: TLS env var {env_var.get('name')}"
                            )
                            break  # Only report once per container

        # Check for initContainers (certificate generation)
        if "initContainers" in pod_spec:
            components_found.append(f"{group_name}: initContainers (cert generation)")

        # Check volumes
        if "volumes" in pod_spec:
            for volume in pod_spec["volumes"]:
                if volume.get("name") in volumes_to_check:
                    components_found.append(
                        f"{group_name}: TLS volume {volume.get('name')}"
                    )

    # Check headGroupSpec
    if "spec" in ray_cluster_yaml and "headGroupSpec" in ray_cluster_yaml["spec"]:
        head_spec = ray_cluster_yaml["spec"]["headGroupSpec"]
        if "template" in head_spec and "spec" in head_spec["template"]:
            check_pod_spec(head_spec["template"]["spec"], "head")
        if head_spec.get("enableIngress") is True:
            components_found.append("head: enableIngress=true")

    # Check workerGroupSpecs
    if "spec" in ray_cluster_yaml and "workerGroupSpecs" in ray_cluster_yaml["spec"]:
        for i, worker_spec in enumerate(ray_cluster_yaml["spec"]["workerGroupSpecs"]):
            if "template" in worker_spec and "spec" in worker_spec["template"]:
                check_pod_spec(worker_spec["template"]["spec"], f"worker[{i}]")

    return len(components_found) > 0, components_found


def _is_cluster_migrated(ray_cluster: dict) -> Tuple[bool, str]:
    """
    Check if a RayCluster has already been migrated.

    A cluster is considered migrated if:
    1. It has the secure-trusted-network annotation set to "true"
    2. It has no TLS/OAuth components

    Returns:
        Tuple[bool, str]: (is_migrated, reason)
    """
    # Check for secure network annotation
    annotations = ray_cluster.get("metadata", {}).get("annotations", {})
    has_annotation = annotations.get(SECURE_NETWORK_ANNOTATION) == "true"

    # Check for TLS/OAuth components
    has_tls_oauth, components = _has_tls_oauth_components(ray_cluster)

    if has_annotation and not has_tls_oauth:
        return True, "Already migrated (has annotation, no TLS/OAuth components)"
    elif has_annotation and has_tls_oauth:
        return False, f"Partially migrated (has annotation but still has: {', '.join(components[:3])})"
    elif not has_annotation and not has_tls_oauth:
        return False, "Needs annotation only (no TLS/OAuth components found)"
    else:
        return False, f"Needs migration (has: {', '.join(components[:3])})"


def _process_ray_cluster_yaml(ray_cluster_yaml: dict) -> dict:
    """
    Processes a RayCluster YAML to remove TLS/OAuth-related components.

    This function removes hardcoded components that are typically added by RHOAI
    for security and OAuth proxy support:
    - TLS-related environment variables (RAY_USE_TLS, RAY_TLS_*)
    - TLS-related volume mounts (ca-vol, server-cert workspace mounts)
    - OAuth proxy sidecar container
    - Certificate generation initContainers
    - TLS/OAuth related volumes
    - Service account configuration

    This processing is applied to both head and worker pod specs.

    Args:
        ray_cluster_yaml (dict): The RayCluster YAML dictionary from Kubernetes API

    Returns:
        dict: The processed YAML with TLS/OAuth components removed
    """
    # Environment variable names to remove (TLS/OAuth related)
    tls_env_vars = {
        "RAY_USE_TLS",
        "RAY_TLS_SERVER_CERT",
        "RAY_TLS_SERVER_KEY",
        "RAY_TLS_CA_CERT",
    }

    # Volume names to remove
    volumes_to_remove = {"ca-vol", "proxy-tls-secret"}

    # Volume mount names to remove from containers
    volume_mounts_to_remove = {"ca-vol", "server-cert"}

    # Container names to remove (sidecar containers)
    containers_to_remove = {"oauth-proxy"}

    def process_container_spec(container_spec):
        """Process a single container spec to remove TLS/OAuth env vars and mounts."""
        if "env" in container_spec:
            # Filter out TLS-related environment variables
            container_spec["env"] = [
                env_var
                for env_var in container_spec["env"]
                if env_var.get("name") not in tls_env_vars
            ]
            # Remove env key if empty
            if not container_spec["env"]:
                del container_spec["env"]

        if "volumeMounts" in container_spec:
            # Filter out TLS/OAuth related volume mounts
            container_spec["volumeMounts"] = [
                mount
                for mount in container_spec["volumeMounts"]
                if mount.get("name") not in volume_mounts_to_remove
            ]
            # Remove volumeMounts key if empty
            if not container_spec["volumeMounts"]:
                del container_spec["volumeMounts"]

    def process_pod_spec(pod_spec):
        """Process a pod spec (in template.spec) to clean up TLS/OAuth components."""
        # Process containers
        if "containers" in pod_spec:
            # Remove sidecar containers like oauth-proxy
            pod_spec["containers"] = [
                container
                for container in pod_spec["containers"]
                if container.get("name") not in containers_to_remove
            ]
            # Process remaining containers to remove TLS env/mounts
            for container in pod_spec["containers"]:
                process_container_spec(container)

        # Remove entire initContainers section
        if "initContainers" in pod_spec:
            del pod_spec["initContainers"]

        # Remove serviceAccountName field
        if "serviceAccountName" in pod_spec:
            del pod_spec["serviceAccountName"]

        # Process volumes
        if "volumes" in pod_spec:
            # Filter out TLS/OAuth related volumes
            pod_spec["volumes"] = [
                volume
                for volume in pod_spec["volumes"]
                if volume.get("name") not in volumes_to_remove
            ]

    # Process headGroupSpec
    if "spec" in ray_cluster_yaml and "headGroupSpec" in ray_cluster_yaml["spec"]:
        head_spec = ray_cluster_yaml["spec"]["headGroupSpec"]
        if "template" in head_spec and "spec" in head_spec["template"]:
            process_pod_spec(head_spec["template"]["spec"])
        # Disable enableIngress if it's set to true
        if head_spec.get("enableIngress") is True:
            head_spec["enableIngress"] = False

    # Process workerGroupSpecs
    if "spec" in ray_cluster_yaml and "workerGroupSpecs" in ray_cluster_yaml["spec"]:
        for worker_spec in ray_cluster_yaml["spec"]["workerGroupSpecs"]:
            if "template" in worker_spec and "spec" in worker_spec["template"]:
                process_pod_spec(worker_spec["template"]["spec"])

    return ray_cluster_yaml


def _get_clusters(
    api_instance,
    core_api,
    cluster_name: Optional[str] = None,
    namespace: Optional[str] = None,
) -> List[dict]:
    """
    Get RayClusters based on the specified scope.

    Args:
        api_instance: CustomObjectsApi instance
        core_api: CoreV1Api instance
        cluster_name: Specific cluster name (requires namespace)
        namespace: Specific namespace (optional, if None queries all namespaces)

    Returns:
        List[dict]: List of RayCluster resources
    """
    clusters = []

    # Case 1: Specific cluster
    if cluster_name:
        if not namespace:
            raise ValueError(
                "Namespace must be specified when targeting a specific cluster"
            )
        try:
            rc = api_instance.get_namespaced_custom_object(
                group="ray.io",
                version="v1",
                namespace=namespace,
                plural="rayclusters",
                name=cluster_name,
            )
            clusters.append(rc)
        except ApiException as e:
            if e.status == 404:
                print(
                    f"RayCluster '{cluster_name}' not found in namespace '{namespace}'"
                )
            else:
                print(
                    f"Error retrieving RayCluster '{cluster_name}' from namespace '{namespace}': {e}"
                )
        return clusters

    # Case 2: All clusters in specific namespace or all namespaces
    if namespace:
        namespace_names = [namespace]
    else:
        try:
            namespaces = core_api.list_namespace()
            namespace_names = [ns.metadata.name for ns in namespaces.items]
        except Exception as e:
            print(f"Error listing namespaces: {e}")
            return clusters

    for ns in namespace_names:
        try:
            rcs = api_instance.list_namespaced_custom_object(
                group="ray.io",
                version="v1",
                namespace=ns,
                plural="rayclusters",
            )
            clusters.extend(rcs.get("items", []))
        except Exception as e:
            if namespace:  # Only print error if user specified a namespace
                print(f"Warning: Could not list RayClusters in namespace '{ns}': {e}")
            continue

    return clusters


def _get_cluster_route(
    api_instance, cluster_name: str, namespace: str
) -> Optional[str]:
    """
    Get the HTTPRoute URL for a RayCluster.

    Looks for HTTPRoute resources in the namespace that are associated with
    the RayCluster (typically named {cluster_name}-head).

    Args:
        api_instance: CustomObjectsApi instance
        cluster_name: Name of the RayCluster
        namespace: Namespace of the RayCluster

    Returns:
        Optional[str]: The route URL if found, None otherwise
    """
    try:
        # Look for HTTPRoute with the expected naming pattern
        route_name = f"{cluster_name}-head"
        route = api_instance.get_namespaced_custom_object(
            group=GATEWAY_API_GROUP,
            version=GATEWAY_API_VERSION,
            namespace=namespace,
            plural="httproutes",
            name=route_name,
        )

        # Extract hostnames from the HTTPRoute spec
        hostnames = route.get("spec", {}).get("hostnames", [])
        if hostnames:
            # Return the first hostname as the route URL
            return f"https://{hostnames[0]}"

    except ApiException:
        # HTTPRoute not found or not accessible - this is normal if gateway-api
        # is not configured or route hasn't been created yet
        pass
    except Exception:
        # Silently ignore other errors - route info is supplementary
        pass

    return None


def _get_cluster_routes(
    api_instance, migrated_clusters: List[Dict]
) -> Dict[str, str]:
    """
    Get HTTPRoute URLs for a list of migrated clusters.

    Args:
        api_instance: CustomObjectsApi instance
        migrated_clusters: List of dicts with 'name' and 'namespace' keys

    Returns:
        Dict[str, str]: Mapping of "name/namespace" to route URL
    """
    routes = {}
    for cluster in migrated_clusters:
        name = cluster["name"]
        ns = cluster["namespace"]
        route_url = _get_cluster_route(api_instance, name, ns)
        if route_url:
            routes[f"{name}/{ns}"] = route_url
    return routes


def _check_cert_manager_installed(api_client) -> Tuple[bool, str]:
    """
    Check if cert-manager is installed on the cluster.

    Checks for:
    1. cert-manager CRDs (certificates.cert-manager.io)
    2. cert-manager namespace
    3. openshift-cert-manager namespace (OpenShift operator)

    Returns:
        Tuple[bool, str]: (is_installed, message)
    """
    # Check for cert-manager CRD
    try:
        api_ext = client.ApiextensionsV1Api(api_client)
        api_ext.read_custom_resource_definition("certificates.cert-manager.io")
        return True, "cert-manager CRD found"
    except ApiException as e:
        if e.status == 404:
            pass  # CRD not found, continue checking
        else:
            pass  # Other error, continue checking
    except Exception:
        pass  # Continue checking other methods

    # Check for cert-manager namespace
    try:
        core_api = client.CoreV1Api(api_client)
        core_api.read_namespace("cert-manager")
        return True, "cert-manager namespace found"
    except ApiException as e:
        if e.status == 404:
            pass  # Namespace not found
        else:
            pass  # Other error
    except Exception:
        pass

    # Check for openshift-cert-manager namespace (OpenShift operator installs here)
    try:
        core_api = client.CoreV1Api(api_client)
        core_api.read_namespace("openshift-cert-manager")
        return True, "openshift-cert-manager namespace found"
    except ApiException as e:
        if e.status == 404:
            pass
        else:
            pass
    except Exception:
        pass

    return False, "cert-manager not detected"


def _check_codeflare_operator_status(api_client) -> Tuple[bool, str]:
    """
    Check if the codeflare-operator is set to Removed in the DataScienceCluster.

    Returns:
        Tuple[bool, str]: (is_removed_or_unmanaged, message)
    """
    try:
        custom_api = client.CustomObjectsApi(api_client)
        
        # List DataScienceClusters
        dscs = custom_api.list_cluster_custom_object(
            group="datasciencecluster.opendatahub.io",
            version="v1",
            plural="datascienceclusters",
        )
        
        if not dscs.get("items"):
            return True, "No DataScienceCluster found (OK to proceed)"
        
        # Check the first DSC (typically there's only one)
        dsc = dscs["items"][0]
        dsc_name = dsc.get("metadata", {}).get("name", "unknown")
        
        # Get codeflare managementState from spec
        codeflare_state = (
            dsc.get("spec", {})
            .get("components", {})
            .get("codeflare", {})
            .get("managementState", "")
        )
        
        if codeflare_state.lower() == "removed":
            return True, f"codeflare is Removed in DSC '{dsc_name}'"
        elif codeflare_state.lower() == "unmanaged":
            return True, f"codeflare is Unmanaged in DSC '{dsc_name}'"
        elif codeflare_state.lower() == "managed":
            return False, f"codeflare is Managed in DSC '{dsc_name}' (should be Removed)"
        elif not codeflare_state:
            return False, f"codeflare managementState not set in DSC '{dsc_name}'"
        else:
            return False, f"codeflare is '{codeflare_state}' in DSC '{dsc_name}'"
            
    except ApiException as e:
        if e.status == 404:
            return True, "DataScienceCluster CRD not found (OK to proceed)"
        else:
            return True, f"Could not check DataScienceCluster (skipping): {e.reason}"
    except Exception as e:
        return True, f"Could not check DataScienceCluster (skipping): {str(e)}"


def _check_permission(api_client, verb: str, resource: str, group: str = "", all_namespaces: bool = True) -> Tuple[bool, str]:
    """
    Check if the current user has a specific permission.

    Args:
        api_client: Kubernetes API client
        verb: The verb to check (list, get, update, etc.)
        resource: The resource type (rayclusters, namespaces, etc.)
        group: The API group (ray.io, gateway.networking.k8s.io, etc.)
        all_namespaces: Whether to check cluster-wide or not

    Returns:
        Tuple[bool, str]: (has_permission, message)
    """
    try:
        auth_api = client.AuthorizationV1Api(api_client)
        
        # Build the resource attributes
        resource_attributes = {
            "verb": verb,
            "resource": resource,
        }
        if group:
            resource_attributes["group"] = group
        if not all_namespaces:
            resource_attributes["namespace"] = "default"
        
        # Create the access review
        review = client.V1SelfSubjectAccessReview(
            spec=client.V1SelfSubjectAccessReviewSpec(
                resource_attributes=resource_attributes
            )
        )
        
        response = auth_api.create_self_subject_access_review(review)
        
        resource_name = f"{resource}.{group}" if group else resource
        if response.status.allowed:
            return True, f"can {verb} {resource_name}"
        else:
            return False, f"cannot {verb} {resource_name}"
            
    except Exception as e:
        return False, f"error checking {verb} {resource}: {str(e)}"


def _run_pre_upgrade_checks(api_client) -> List[Dict[str, any]]:
    """
    Run pre-upgrade checks to identify potential issues.

    Returns:
        List[Dict]: List of check results with 'name', 'passed', 'message' keys
    """
    checks = []

    # Permission checks for pre-upgrade
    permission_checks = [
        ("list", "namespaces", "", "List namespaces"),
        ("list", "rayclusters", "ray.io", "List RayClusters"),
        ("get", "rayclusters", "ray.io", "Get RayClusters"),
        ("update", "rayclusters", "ray.io", "Update RayClusters"),
    ]
    
    all_permissions_ok = True
    permission_messages = []
    
    for verb, resource, group, desc in permission_checks:
        has_perm, msg = _check_permission(api_client, verb, resource, group)
        if not has_perm:
            all_permissions_ok = False
        permission_messages.append(f"{desc}: {'OK' if has_perm else 'DENIED'}")
    
    checks.append({
        "name": "Permissions",
        "passed": all_permissions_ok,
        "message": "All required permissions granted" if all_permissions_ok else "Missing permissions",
        "required": True,
        "help": "Missing permissions: " + ", ".join([m for m in permission_messages if "DENIED" in m]) if not all_permissions_ok else "",
        "details": permission_messages,
    })

    # Check cert-manager installation
    cert_manager_installed, cert_manager_msg = _check_cert_manager_installed(api_client)
    checks.append({
        "name": "cert-manager",
        "passed": cert_manager_installed,
        "message": cert_manager_msg,
        "required": True,
        "help": "cert-manager is required for RHOAI 3.x. "
                "Install it via OperatorHub before proceeding with the upgrade."
    })
    
    # Check codeflare-operator status in DSC
    codeflare_ok, codeflare_msg = _check_codeflare_operator_status(api_client)
    checks.append({
        "name": "codeflare-operator",
        "passed": codeflare_ok,
        "message": codeflare_msg,
        "required": True,
        "help": "Set codeflare to Removed in your DataScienceCluster before upgrading: "
                "oc patch datasciencecluster <name> --type merge -p "
                "'{\"spec\":{\"components\":{\"codeflare\":{\"managementState\":\"Removed\"}}}}'"
    })

    return checks


def pre_upgrade(
    output_dir: Optional[str] = None,
    cluster_name: Optional[str] = None,
    namespace: Optional[str] = None,
) -> List[str]:
    """
    Backup RayCluster configurations before RHOAI upgrade.

    This function:
    1. Runs pre-flight checks to verify the cluster is ready for upgrade
    2. Exports RayClusters to YAML files for backup purposes

    It does NOT delete any clusters - it only creates backup files.

    This operation is idempotent - running it multiple times will simply
    overwrite the backup files.

    Args:
        output_dir: Directory to save backup YAML files (prompts if not provided)
        cluster_name: Specific cluster to backup (requires namespace)
        namespace: Specific namespace to backup (optional)

    Returns:
        List[str]: List of backup file paths created
    """
    # Prompt for output directory if not provided
    if not output_dir:
        default_dir = "./raycluster-backups"
        user_input = input(f"Enter backup directory [{default_dir}]: ").strip()
        output_dir = user_input if user_input else default_dir
        print()

    try:
        config_check()
    except Exception as e:
        raise RuntimeError(f"Failed to connect to Kubernetes cluster: {e}")

    api_client = get_api_client()
    api_instance = client.CustomObjectsApi(api_client)
    core_api = client.CoreV1Api(api_client)

    # Run pre-flight checks
    print("Running pre-upgrade checks...")
    print("-" * 60)

    checks = _run_pre_upgrade_checks(api_client)
    all_passed = True
    has_required_failures = False

    for check in checks:
        status = "[OK]" if check["passed"] else "[FAIL]"
        print(f"  {status} {check['name']}: {check['message']}")
        
        # Show details if present (e.g., individual permission results)
        if check.get("details") and not check["passed"]:
            for detail in check["details"]:
                print(f"       - {detail}")
        
        if not check["passed"]:
            all_passed = False
            if check.get("required", False):
                has_required_failures = True
                if check.get("help"):
                    print(f"       {check['help']}")

    print("-" * 60)

    if has_required_failures:
        print("\nPre-upgrade checks failed. Please resolve the issues above before")
        print("proceeding with the RHOAI upgrade.")
        print()
        print("WARNING: Proceeding with the RHOAI upgrade without resolving these issues")
        print("may result in your Ray infrastructure becoming unavailable or unrecoverable.")
        return []
    elif all_passed:
        print("All pre-upgrade checks passed.\n")
    else:
        print("Pre-upgrade checks completed with warnings.\n")

    # Create output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        print(f"Created backup directory: {output_dir}")

    # Get clusters based on scope
    clusters = _get_clusters(api_instance, core_api, cluster_name, namespace)

    if not clusters:
        print("No RayClusters found to backup")
        return []

    # Describe the scope
    if cluster_name:
        scope_msg = f"cluster '{cluster_name}' in namespace '{namespace}'"
    elif namespace:
        scope_msg = f"all clusters in namespace '{namespace}'"
    else:
        scope_msg = "all clusters across all namespaces"

    print(f"\nBacking up {len(clusters)} RayCluster(s) ({scope_msg})\n")

    saved_files = []

    for rc in clusters:
        try:
            # Make a copy to avoid modifying the original
            rc_copy = copy.deepcopy(rc)

            # Remove auto-generated fields
            remove_autogenerated_fields(rc_copy)

            # Apply processing to remove TLS/OAuth components (for clean backup)
            rc_copy = _process_ray_cluster_yaml(rc_copy)

            # Generate output filename
            name = rc_copy["metadata"]["name"]
            ns = rc_copy["metadata"]["namespace"]
            output_filename = os.path.join(output_dir, f"raycluster-{name}-{ns}.yaml")

            # Write to file
            with open(output_filename, "w") as outfile:
                yaml.dump(rc_copy, outfile, default_flow_style=False)

            saved_files.append(output_filename)
            print(f"  Backed up: {name} (namespace: {ns}) -> {output_filename}")

        except Exception as e:
            name = rc.get("metadata", {}).get("name", "unknown")
            print(f"  Error backing up '{name}': {e}")
            continue

    print(f"\nBackup complete: {len(saved_files)} RayCluster(s) saved to {output_dir}")
    print("\nNext steps:")
    print("  1. Perform the RHOAI upgrade")
    print("  2. Run 'post-upgrade' to migrate the RayClusters")
    return saved_files


def post_upgrade(
    cluster_name: Optional[str] = None,
    namespace: Optional[str] = None,
    dry_run: bool = False,
    auto_confirm: bool = False,
) -> Dict[str, int]:
    """
    Migrate RayClusters after RHOAI upgrade.

    This function modifies existing RayClusters by:
    - Removing TLS/OAuth components (env vars, sidecars, init containers, volumes)
    - Adding the odh.ray.io/secure-trusted-network annotation

    This operation is idempotent - clusters that are already migrated will be
    skipped automatically.

    Recommended workflow:
    1. First test on a single cluster: --cluster NAME --namespace NS
    2. Then proceed with namespace: --namespace NS
    3. Finally migrate all: (no flags)

    Args:
        cluster_name: Specific cluster to migrate (requires namespace)
        namespace: Specific namespace to migrate (if not specified, targets all namespaces)
        dry_run: If True, show what would be changed without making changes
        auto_confirm: If True, skip confirmation prompt

    Returns:
        Dict[str, int]: Counts of migrated, skipped, and failed clusters
    """
    try:
        config_check()
    except Exception as e:
        raise RuntimeError(f"Failed to connect to Kubernetes cluster: {e}")

    # Validate arguments
    if cluster_name and not namespace:
        raise ValueError(
            "Namespace must be specified when migrating a specific cluster"
        )

    api_instance = client.CustomObjectsApi(get_api_client())
    core_api = client.CoreV1Api(get_api_client())

    # Get clusters based on scope
    clusters = _get_clusters(api_instance, core_api, cluster_name, namespace)

    if not clusters:
        print("No RayClusters found to migrate")
        return {"migrated": 0, "skipped": 0, "failed": 0}

    # Describe the scope
    if cluster_name:
        scope_msg = f"cluster '{cluster_name}' in namespace '{namespace}'"
    elif namespace:
        scope_msg = f"all clusters in namespace '{namespace}'"
    else:
        scope_msg = "all clusters across all namespaces"

    if dry_run:
        print("=== DRY RUN MODE - No changes will be made ===\n")

    print(f"Analyzing {len(clusters)} RayCluster(s) ({scope_msg})\n")

    # Analyze clusters and categorize them
    to_migrate = []
    already_migrated = []

    for rc in clusters:
        name = rc.get("metadata", {}).get("name", "unknown")
        ns = rc.get("metadata", {}).get("namespace", "unknown")
        is_migrated, _ = _is_cluster_migrated(rc)

        if is_migrated:
            already_migrated.append({"rc": rc, "name": name, "namespace": ns})
            print(f"  [SKIP] {name} (ns: {ns}) - already migrated")
        else:
            to_migrate.append({"rc": rc, "name": name, "namespace": ns})
            print(f"  [MIGRATE] {name} (ns: {ns}) - needs migration")

    print(f"\nSummary: {len(to_migrate)} to migrate, {len(already_migrated)} already migrated")

    if not to_migrate:
        print("\nAll clusters are already migrated. Nothing to do.")
        return {"migrated": 0, "skipped": len(already_migrated), "failed": 0}

    # Confirmation for non-dry-run
    if not dry_run and not auto_confirm:
        # Show scope warning for multi-cluster operations
        if not cluster_name:
            print("\n" + "=" * 60)
            if namespace:
                print(f"WARNING: You are about to migrate ALL clusters in namespace '{namespace}'")
            else:
                print("WARNING: You are about to migrate ALL clusters across ALL namespaces")
            print("=" * 60)

        print(f"\nThe following {len(to_migrate)} cluster(s) will be migrated:")
        for item in to_migrate:
            print(f"  - {item['name']} (namespace: {item['namespace']})")

        print("\nIMPORTANT: Migration will cause temporary downtime for each RayCluster")
        print("as the cluster pods are restarted with the updated configuration.")

        response = input("\nProceed with migration? (yes/no): ").strip().lower()
        if response not in ["yes", "y"]:
            print("Migration cancelled.")
            return {"migrated": 0, "skipped": len(already_migrated), "failed": 0}
        print()

    # Perform migration
    migrated_count = 0
    failed_count = 0
    successfully_migrated = []  # Track for route lookup

    for item in to_migrate:
        rc = item["rc"]
        name = item["name"]
        ns = item["namespace"]

        try:
            if dry_run:
                print(f"  [DRY RUN] Would migrate: {name} (ns: {ns})")
                migrated_count += 1
                continue

            # Make a copy
            rc_copy = copy.deepcopy(rc)

            # Save fields needed for replace operation
            resource_version = rc_copy.get("metadata", {}).get("resourceVersion")
            uid = rc_copy.get("metadata", {}).get("uid")

            # Remove auto-generated fields
            remove_autogenerated_fields(rc_copy)

            # Process to remove TLS/OAuth components
            rc_cleaned = _process_ray_cluster_yaml(rc_copy)

            # Restore fields needed for replace operation
            if "metadata" not in rc_cleaned:
                rc_cleaned["metadata"] = {}
            if resource_version:
                rc_cleaned["metadata"]["resourceVersion"] = resource_version
            if uid:
                rc_cleaned["metadata"]["uid"] = uid

            # Add secure trusted network annotation
            if "annotations" not in rc_cleaned["metadata"]:
                rc_cleaned["metadata"]["annotations"] = {}
            rc_cleaned["metadata"]["annotations"][SECURE_NETWORK_ANNOTATION] = "true"

            # Apply the changes using replace
            api_instance.replace_namespaced_custom_object(
                group="ray.io",
                version="v1",
                namespace=ns,
                plural="rayclusters",
                name=name,
                body=rc_cleaned,
            )
            print(f"  [OK] Migrated: {name} (ns: {ns})")
            migrated_count += 1
            successfully_migrated.append({"name": name, "namespace": ns})

        except Exception as e:
            print(f"  [FAIL] {name} (ns: {ns}): {e}")
            failed_count += 1

    # Print final summary
    print(f"\n{'='*60}")
    if dry_run:
        print(f"DRY RUN Summary:")
        print(f"  Would migrate: {migrated_count}")
    else:
        print(f"Migration Summary:")
        print(f"  Migrated: {migrated_count}")
    print(f"  Skipped (already migrated): {len(already_migrated)}")
    print(f"  Failed: {failed_count}")

    # Show routes for successfully migrated clusters
    if successfully_migrated and not dry_run:
        print(f"\n{'='*60}")
        print("RayCluster Routes (Gateway API):")
        print("Note: Routes may take a moment to become available after migration.")
        print("-" * 60)

        routes = _get_cluster_routes(api_instance, successfully_migrated)
        for cluster in successfully_migrated:
            key = f"{cluster['name']}/{cluster['namespace']}"
            route_url = routes.get(key)
            if route_url:
                print(f"  {cluster['name']} (ns: {cluster['namespace']})")
                print(f"    Dashboard: {route_url}")
            else:
                print(f"  {cluster['name']} (ns: {cluster['namespace']})")
                print(f"    Route: Not yet available (check again shortly)")

    return {
        "migrated": migrated_count,
        "skipped": len(already_migrated),
        "failed": failed_count,
    }


def list_ray_clusters(
    namespace: Optional[str] = None, output_format: str = "table"
) -> List[Dict]:
    """
    Lists all RayClusters with their migration status.

    This function helps you understand which clusters need migration and which
    are already migrated.

    Args:
        namespace: Specific namespace to query (optional, if None queries all)
        output_format: Output format - "table" (default) or "yaml"

    Returns:
        List[Dict]: List of RayCluster information dictionaries
    """
    try:
        config_check()
    except Exception as e:
        raise RuntimeError(f"Failed to connect to Kubernetes cluster: {e}")

    api_instance = client.CustomObjectsApi(get_api_client())
    core_api = client.CoreV1Api(get_api_client())

    clusters = _get_clusters(api_instance, core_api, namespace=namespace)
    clusters_info = []

    for rc in clusters:
        name = rc.get("metadata", {}).get("name", "unknown")
        ns = rc.get("metadata", {}).get("namespace", "unknown")
        status = rc.get("status", {}).get("state", "unknown")

        # Check migration status
        is_migrated, migration_reason = _is_cluster_migrated(rc)
        has_tls_oauth, components = _has_tls_oauth_components(rc)

        # Extract resource information
        head_resources = {}
        worker_resources = {}
        num_workers = 0

        try:
            head_spec = rc["spec"]["headGroupSpec"]["template"]["spec"]["containers"][
                0
            ]["resources"]
            head_resources = {
                "cpu_request": head_spec.get("requests", {}).get("cpu", "N/A"),
                "cpu_limit": head_spec.get("limits", {}).get("cpu", "N/A"),
                "memory_request": head_spec.get("requests", {}).get("memory", "N/A"),
                "memory_limit": head_spec.get("limits", {}).get("memory", "N/A"),
            }

            worker_spec = rc["spec"]["workerGroupSpecs"][0]
            num_workers = worker_spec.get("replicas", 0)
            worker_container_resources = worker_spec["template"]["spec"]["containers"][
                0
            ]["resources"]
            worker_resources = {
                "cpu_request": worker_container_resources.get("requests", {}).get(
                    "cpu", "N/A"
                ),
                "cpu_limit": worker_container_resources.get("limits", {}).get(
                    "cpu", "N/A"
                ),
                "memory_request": worker_container_resources.get("requests", {}).get(
                    "memory", "N/A"
                ),
                "memory_limit": worker_container_resources.get("limits", {}).get(
                    "memory", "N/A"
                ),
            }
        except (KeyError, IndexError):
            pass

        cluster_info = {
            "name": name,
            "namespace": ns,
            "status": status,
            "num_workers": num_workers,
            "migrated": is_migrated,
            "migration_status": migration_reason,
            "tls_oauth_components": components if has_tls_oauth else [],
            "head_resources": head_resources,
            "worker_resources": worker_resources,
        }
        clusters_info.append(cluster_info)

    # Display results
    if output_format == "yaml":
        print(yaml.dump(clusters_info, default_flow_style=False))
    else:
        if not clusters_info:
            print("No RayClusters found")
            return clusters_info

        print(f"\nFound {len(clusters_info)} RayCluster(s):\n")
        print(
            f"{'Name':<25} {'Namespace':<18} {'Status':<12} {'Workers':<8} {'Migration Status':<30}"
        )
        print("-" * 100)

        migrated_count = 0
        needs_migration_count = 0

        for cluster in clusters_info:
            migration_indicator = "[OK]" if cluster["migrated"] else "[NEEDS MIGRATION]"
            if cluster["migrated"]:
                migrated_count += 1
            else:
                needs_migration_count += 1

            print(
                f"{cluster['name']:<25} "
                f"{cluster['namespace']:<18} "
                f"{cluster['status']:<12} "
                f"{cluster['num_workers']:<8} "
                f"{migration_indicator}"
            )

        print(f"\nMigration Summary: {migrated_count} migrated, {needs_migration_count} need migration")

    return clusters_info


def delete_ray_clusters(
    cluster_name: Optional[str] = None,
    namespace: Optional[str] = None,
    all_clusters: bool = False,
    dry_run: bool = False,
    auto_confirm: bool = False,
) -> Dict[str, int]:
    """
    Delete RayClusters from the cluster.

    This is an advanced operation for removing clusters entirely.
    For normal migration workflow, use pre-upgrade and post-upgrade instead.

    Args:
        cluster_name: Specific cluster to delete (requires namespace)
        namespace: Namespace to delete from
        all_clusters: If True, delete all clusters in scope
        dry_run: If True, show what would be deleted without deleting
        auto_confirm: If True, skip confirmation prompt

    Returns:
        Dict[str, int]: Counts of deleted and failed clusters
    """
    try:
        config_check()
    except Exception as e:
        raise RuntimeError(f"Failed to connect to Kubernetes cluster: {e}")

    if cluster_name and not namespace:
        raise ValueError(
            "Namespace must be specified when deleting a specific cluster"
        )

    if not cluster_name and not all_clusters:
        raise ValueError(
            "Either specify a cluster name or use --all to delete multiple clusters"
        )

    api_instance = client.CustomObjectsApi(get_api_client())
    core_api = client.CoreV1Api(get_api_client())

    clusters = _get_clusters(api_instance, core_api, cluster_name, namespace)

    if not clusters:
        print("No RayClusters found to delete")
        return {"deleted": 0, "failed": 0}

    if dry_run:
        print("=== DRY RUN MODE - No clusters will be deleted ===\n")

    print(f"Found {len(clusters)} RayCluster(s) to delete\n")

    # Confirmation
    if not dry_run and not auto_confirm:
        print("WARNING: This will PERMANENTLY DELETE the following RayCluster(s):")
        for rc in clusters:
            name = rc.get("metadata", {}).get("name", "unknown")
            ns = rc.get("metadata", {}).get("namespace", "unknown")
            print(f"  - {name} (namespace: {ns})")

        print("\nThis operation is IRREVERSIBLE!")
        response = input("\nDelete these clusters? (yes/no): ").strip().lower()
        if response not in ["yes", "y"]:
            print("Delete cancelled.")
            return {"deleted": 0, "failed": 0}
        print()

    deleted_count = 0
    failed_count = 0

    for rc in clusters:
        name = rc.get("metadata", {}).get("name", "unknown")
        ns = rc.get("metadata", {}).get("namespace", "unknown")

        try:
            if dry_run:
                print(f"  [DRY RUN] Would delete: {name} (ns: {ns})")
                deleted_count += 1
            else:
                api_instance.delete_namespaced_custom_object(
                    group="ray.io",
                    version="v1",
                    namespace=ns,
                    plural="rayclusters",
                    name=name,
                )
                print(f"  Deleted: {name} (ns: {ns})")
                deleted_count += 1
        except Exception as e:
            print(f"  Failed to delete {name} (ns: {ns}): {e}")
            failed_count += 1

    if dry_run:
        print(f"\n[DRY RUN] Would delete: {deleted_count}, Would fail: {failed_count}")
    else:
        print(f"\nDeleted: {deleted_count}, Failed: {failed_count}")

    return {"deleted": deleted_count, "failed": failed_count}


def import_ray_clusters(
    source_path: str, force: bool = False, dry_run: bool = False
) -> List[Dict]:
    """
    Import RayClusters from backup YAML files.

    This is an advanced operation for restoring clusters from backups.
    Use this if you need to restore clusters after the pre-upgrade backup.

    Args:
        source_path: Path to YAML file or directory containing YAML files
        force: Force apply in case of conflicts
        dry_run: Preview what would be imported without applying

    Returns:
        List[Dict]: Results for each import attempt
    """
    if not os.path.exists(source_path):
        raise ValueError(f"Source path does not exist: {source_path}")

    try:
        config_check()
    except Exception as e:
        raise RuntimeError(f"Failed to connect to Kubernetes cluster: {e}")

    results = []
    files_to_process = []

    if os.path.isfile(source_path):
        if source_path.endswith(".yaml") or source_path.endswith(".yml"):
            files_to_process.append(source_path)
        else:
            raise ValueError(f"File is not a YAML file: {source_path}")
    elif os.path.isdir(source_path):
        for filename in os.listdir(source_path):
            if filename.endswith(".yaml") or filename.endswith(".yml"):
                files_to_process.append(os.path.join(source_path, filename))
    else:
        raise ValueError(f"Source path is neither file nor directory: {source_path}")

    if not files_to_process:
        print("No YAML files found to import")
        return results

    if dry_run:
        print("=== DRY RUN MODE - No changes will be applied ===\n")

    try:
        crds = DynamicClient(get_api_client()).resources
        api_instance = crds.get(api_version="ray.io/v1", kind="RayCluster")
    except Exception as e:
        raise RuntimeError(f"Failed to initialize DynamicClient for RayCluster: {e}")

    for yaml_file in files_to_process:
        try:
            with open(yaml_file, "r") as f:
                yaml_documents = yaml.safe_load_all(f)

                for doc in yaml_documents:
                    if doc is None:
                        continue

                    try:
                        name = doc.get("metadata", {}).get("name", "unknown")
                        ns = doc.get("metadata", {}).get("namespace", "default")
                        kind = doc.get("kind", "")

                        if kind != "RayCluster":
                            print(f"  Skipping non-RayCluster: {name} (kind: {kind})")
                            continue

                        # Add secure network annotation
                        if "metadata" not in doc:
                            doc["metadata"] = {}
                        if "annotations" not in doc["metadata"]:
                            doc["metadata"]["annotations"] = {}
                        doc["metadata"]["annotations"][SECURE_NETWORK_ANNOTATION] = "true"

                        if dry_run:
                            message = f"[DRY RUN] Would import: {name} (ns: {ns})"
                        else:
                            api_instance.server_side_apply(
                                field_manager=CF_SDK_FIELD_MANAGER,
                                group="ray.io",
                                version="v1",
                                namespace=ns,
                                plural="rayclusters",
                                body=doc,
                                force_conflicts=force,
                            )
                            message = f"Imported: {name} (ns: {ns})"

                        results.append({
                            "cluster_name": name,
                            "namespace": ns,
                            "file": yaml_file,
                            "status": "success",
                            "message": message,
                        })
                        print(f"  {message}")

                    except Exception as e:
                        name = doc.get("metadata", {}).get("name", "unknown")
                        ns = doc.get("metadata", {}).get("namespace", "default")
                        results.append({
                            "cluster_name": name,
                            "namespace": ns,
                            "file": yaml_file,
                            "status": "error",
                            "message": str(e),
                        })
                        print(f"  Error importing {name}: {e}")

        except Exception as e:
            results.append({
                "cluster_name": "unknown",
                "namespace": "unknown",
                "file": yaml_file,
                "status": "error",
                "message": str(e),
            })
            print(f"  Error reading {yaml_file}: {e}")

    success = sum(1 for r in results if r["status"] == "success")
    errors = sum(1 for r in results if r["status"] == "error")

    if dry_run:
        print(f"\n[DRY RUN] Would import: {success}, Would fail: {errors}")
    else:
        print(f"\nImported: {success}, Failed: {errors}")

    return results


def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="RayCluster Migration Tool for RHOAI 2.x to RHOAI 3.x",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
RECOMMENDED MIGRATION WORKFLOW:

  1. BEFORE UPGRADE - Backup your clusters:

     # Backup all clusters (you'll be prompted for backup directory)
     %(prog)s pre-upgrade

     # Or specify the backup directory directly
     %(prog)s pre-upgrade ./my-backup-dir

     # Backup a specific namespace
     %(prog)s pre-upgrade --namespace my-ns

     # Backup a single cluster
     %(prog)s pre-upgrade --cluster my-cluster --namespace my-ns

  2. PERFORM THE RHOAI UPGRADE

  3. AFTER UPGRADE - Migrate your clusters:

     # Test with a single cluster first (always use --dry-run first!)
     %(prog)s post-upgrade --cluster my-cluster --namespace my-ns --dry-run
     %(prog)s post-upgrade --cluster my-cluster --namespace my-ns

     # Then migrate the whole namespace
     %(prog)s post-upgrade --namespace my-ns --dry-run
     %(prog)s post-upgrade --namespace my-ns

     # Or migrate everything (you'll be prompted to confirm)
     %(prog)s post-upgrade --dry-run
     %(prog)s post-upgrade

  DISCOVERY - See what needs migration:
     %(prog)s list
     %(prog)s list --namespace my-ns

All operations are idempotent and safe to run multiple times.
        """,
    )

    subparsers = parser.add_subparsers(dest="command", help="Command to execute")

    # Pre-upgrade command
    pre_parser = subparsers.add_parser(
        "pre-upgrade",
        help="Backup RayCluster configurations BEFORE the RHOAI upgrade",
        description="Runs pre-flight checks and creates backup YAML files of your "
        "RayCluster configurations. Run this BEFORE performing the RHOAI upgrade.",
    )
    pre_parser.add_argument(
        "output_dir",
        nargs="?",
        default=None,
        help="Directory to save backup YAML files (you'll be prompted if not provided)",
    )
    pre_parser.add_argument(
        "--cluster",
        "-c",
        dest="cluster_name",
        help="Backup a specific cluster (requires --namespace)",
    )
    pre_parser.add_argument(
        "--namespace",
        "-n",
        help="Backup all clusters in this namespace",
    )

    # Post-upgrade command
    post_parser = subparsers.add_parser(
        "post-upgrade",
        help="Migrate RayClusters AFTER the RHOAI upgrade",
        description="Migrates RayClusters by removing TLS/OAuth components and adding "
        "the secure-trusted-network annotation. Run this AFTER the RHOAI upgrade.",
    )
    post_parser.add_argument(
        "--cluster",
        "-c",
        dest="cluster_name",
        help="Migrate a specific cluster (requires --namespace)",
    )
    post_parser.add_argument(
        "--namespace",
        "-n",
        help="Migrate all clusters in this namespace (if omitted, targets all namespaces)",
    )
    post_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be changed without making changes",
    )
    post_parser.add_argument(
        "--yes",
        "-y",
        action="store_true",
        help="Skip confirmation prompt",
    )

    # List command
    list_parser = subparsers.add_parser(
        "list",
        help="List RayClusters and their migration status",
        description="Shows all RayClusters and whether they need migration.",
    )
    list_parser.add_argument(
        "--namespace",
        "-n",
        help="List clusters in this namespace only",
    )
    list_parser.add_argument(
        "--format",
        "-f",
        choices=["table", "yaml"],
        default="table",
        help="Output format (default: table)",
    )

    # Delete command (advanced)
    delete_parser = subparsers.add_parser(
        "delete",
        help="[Advanced] Delete RayClusters from the cluster",
        description="Permanently deletes RayClusters. This is an advanced operation - "
        "for normal migration, use pre-upgrade and post-upgrade instead.",
    )
    delete_parser.add_argument(
        "--cluster",
        "-c",
        dest="cluster_name",
        help="Delete a specific cluster (requires --namespace)",
    )
    delete_parser.add_argument(
        "--namespace",
        "-n",
        help="Delete from this namespace",
    )
    delete_parser.add_argument(
        "--all",
        action="store_true",
        dest="all_clusters",
        help="Delete all clusters in scope",
    )
    delete_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be deleted",
    )
    delete_parser.add_argument(
        "--yes",
        "-y",
        action="store_true",
        help="Skip confirmation prompt",
    )

    # Import command (advanced)
    import_parser = subparsers.add_parser(
        "import",
        help="[Advanced] Import RayClusters from backup YAML files",
        description="Restores RayClusters from backup files. This is an advanced operation - "
        "for normal migration, use pre-upgrade and post-upgrade instead.",
    )
    import_parser.add_argument(
        "source_path", help="Path to YAML file or directory containing backups"
    )
    import_parser.add_argument(
        "--force",
        action="store_true",
        help="Force apply in case of conflicts",
    )
    import_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be imported",
    )

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    try:
        if args.command == "pre-upgrade":
            pre_upgrade(
                output_dir=args.output_dir,
                cluster_name=args.cluster_name,
                namespace=args.namespace,
            )
        elif args.command == "post-upgrade":
            post_upgrade(
                cluster_name=args.cluster_name,
                namespace=args.namespace,
                dry_run=args.dry_run,
                auto_confirm=args.yes,
            )
        elif args.command == "list":
            list_ray_clusters(namespace=args.namespace, output_format=args.format)
        elif args.command == "delete":
            delete_ray_clusters(
                cluster_name=args.cluster_name,
                namespace=args.namespace,
                all_clusters=args.all_clusters,
                dry_run=args.dry_run,
                auto_confirm=args.yes,
            )
        elif args.command == "import":
            import_ray_clusters(
                source_path=args.source_path,
                force=args.force,
                dry_run=args.dry_run,
            )
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
