name: Label new issues as needs-triage and add to CodeFlare Sprint Board
on:
  issues:
    types:
      - opened
jobs:
  add_label:
    name: Add needs-triage label to new issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - run: gh issue edit ${{ github.event.issue.number }} --add-label "triage/needs-triage"
        env:
          GH_TOKEN: ${{ github.token }}

  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/project-codeflare/projects/8
          github-token: ${{ secrets.CODEFLARE_MACHINE_ACCOUNT_TOKEN }}
