# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.4
        pip install pytest-mock==3.6.1
        pip install coverage
        pip install black==22.3.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check formatting with black
      run: |
        black --check .
    - name: Test with pytest and check coverage
      run: |
        coverage run -m --source=src pytest -v tests/unit_test.py
        coverage=$(coverage report -m | tail -1 | tail -c 4 | head -c 2)
        if (( $coverage < 90 )); then exit 1; else echo "Coverage passed, ${coverage}%"; fi
