name: Snyk Security
on:
  push:
    branches:
      - main
      - test-odh-notebooks-sync

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Monitor and Test multiple projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
        run: |
          echo "Fetching tags"
          git fetch origin 'refs/tags/*:refs/tags/*'
          echo "Authenticating with Snyk"
          snyk auth ${SNYK_TOKEN}
          list_of_released_tags=("v0.23.1")
          for project in "${list_of_released_tags[@]}"; do
            echo "Scanning project: codeflare-sdk/$project"
            git checkout $project
            snyk monitor --all-projects --exclude=requirements.txt --org=${SNYK_ORG} --target-reference="$(git describe --tags)"
          done
